import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { getSiteStats } from "../services/stats-service.ts";
import type { GlobalStats, StatsResponse, TopicStats } from "../types/index.ts";
import "./StatsPage.css";

function emptyGlobal(): GlobalStats {
  return {
    topicCount: 0,
    eventCount: 0,
    branchCount: 0,
    sourceCount: 0,
    eventsWithContent: 0,
    eventsWithImages: 0,
    generatedBy: {
      preseed: 0,
      chat: 0,
      enrichment: 0,
      expansion: 0,
      seed: 0,
    },
  };
}

function metricCards(stats: GlobalStats | TopicStats) {
  return [
    { label: "Topics", value: "topicCount" in stats ? stats.topicCount : 1 },
    { label: "Events", value: stats.eventCount },
    { label: "Branches", value: stats.branchCount },
    { label: "Sources", value: stats.sourceCount },
    { label: "Events with content", value: stats.eventsWithContent },
    { label: "Events with images", value: stats.eventsWithImages },
  ];
}

export default function StatsPage() {
  const [searchParams] = useSearchParams();
  const returnTopicId = searchParams.get("topic") || "ww2";

  const [data, setData] = useState<StatsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedTopic, setSelectedTopic] = useState<string>("__all__");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      setError(null);
      try {
        const stats = await getSiteStats();
        if (!cancelled) setData(stats);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to load stats");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, []);

  const selected = useMemo(() => {
    if (!data) return null;
    if (selectedTopic === "__all__") return data.global;
    return data.topics.find((topic) => topic.topicId === selectedTopic) || null;
  }, [data, selectedTopic]);

  if (loading) {
    return (
      <div className="stats-page">
        <div className="stats-loading">Loading site statistics...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="stats-page">
        <header className="stats-header">
          <h1>Site Stats</h1>
          <Link to={`/topic/${returnTopicId}`} className="stats-back-link">Back to timeline</Link>
        </header>
        <div className="stats-error">{error}</div>
      </div>
    );
  }

  const active = selected || data?.global || emptyGlobal();

  return (
    <div className="stats-page">
      <header className="stats-header">
        <div>
          <h1>Site Stats</h1>
          <p className="stats-generated">Generated: {data?.generatedAt ? new Date(data.generatedAt).toLocaleString() : "-"}</p>
        </div>
        <Link to={`/topic/${returnTopicId}`} className="stats-back-link">Back to timeline</Link>
      </header>

      <section className="stats-controls">
        <label htmlFor="stats-topic-filter">Scope</label>
        <select
          id="stats-topic-filter"
          value={selectedTopic}
          onChange={(e) => setSelectedTopic(e.target.value)}
        >
          <option value="__all__">All topics</option>
          {(data?.topics || []).map((topic) => (
            <option key={topic.topicId} value={topic.topicId}>{topic.topicName}</option>
          ))}
        </select>
      </section>

      {(data?.warnings || []).length > 0 && (
        <div className="stats-warning">
          {data?.warnings.join(". ")}
        </div>
      )}

      <section className="stats-cards">
        {metricCards(active).map((metric) => (
          <article key={metric.label} className="stats-card">
            <div className="stats-card-label">{metric.label}</div>
            <div className="stats-card-value">{metric.value.toLocaleString()}</div>
          </article>
        ))}
      </section>

      <section className="stats-breakdown">
        <h2>Generated By</h2>
        <div className="stats-breakdown-grid">
          {Object.entries(active.generatedBy).map(([key, value]) => (
            <div key={key} className="stats-breakdown-item">
              <span>{key}</span>
              <strong>{value.toLocaleString()}</strong>
            </div>
          ))}
        </div>
      </section>

      {data && data.topics.length === 0 && (
        <div className="stats-empty">No topic data available yet.</div>
      )}
    </div>
  );
}
